# Generated by Django 3.2 on 2021-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('highschool', 'Highschool'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctorate', 'Doctorate')], default='bachelor', max_length=20),
        ),
    ]
