# Generated by Django 3.2 on 2021-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
